/*
 * SUNFISH Blockchain API - Storage of access control policies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: S.Ferdous@soton.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



package org.sunfish.icsp.common.rest.model.ri;


import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * ServiceresponseList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-23T08:20:44.040Z")
public class ServiceresponseList {
  private String policyId = null;

  private String policy = null;

  public ServiceresponseList id(final String id) {
    this.policyId = id;
    return this;
  }

   /**
   * Specifies the policyId of the policy.
   * @return policyId
  **/
  @ApiModelProperty(example = "null", required = true, value = "Specifies the policyId of the policy.")
  public String getPolicyId() {
    return policyId;
  }

  public void setPolicyId(final String id) {
    this.policyId = id;
  }

  public ServiceresponseList policy(final String policy) {
    this.policy = policy;
    return this;
  }

   /**
   * BASE64-enocded data of the policy.
   * @return policy
  **/
  @ApiModelProperty(example = "null", required = true, value = "BASE64-enocded data of the policy.")
  public String getPolicy() {
    return policy;
  }

  public void setPolicy(final String policy) {
    this.policy = policy;
  }


  @Override
  public boolean equals(final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ServiceresponseList serviceresponseList = (ServiceresponseList) o;
    return Objects.equals(this.policyId, serviceresponseList.policyId) &&
           Objects.equals(this.policy, serviceresponseList.policy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyId, policy);
  }


  @Override
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ServiceresponseList {\n");

    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

