/*
 * SUNFISH Blockchain API - Storage of access control policies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: S.Ferdous@soton.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.sunfish.icsp.common.rest.model.ri;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * HTTP response containing the list of policies for the service.
 */
@ApiModel(description = "HTTP response containing the list of policies for the service.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-23T08:20:44.040Z")
public class ServiceResponse {

  private List<ServiceresponseList> list = new ArrayList<>();

  public ServiceResponse list(final List<ServiceresponseList> list) {
    this.list = list;
    return this;
  }

  public ServiceResponse addListItem(final ServiceresponseList listItem) {
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<ServiceresponseList> getList() {
    return list;
  }

  public void setList(final List<ServiceresponseList> list) {
    this.list = list;
  }


  @Override
  public boolean equals(final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ServiceResponse serviceResponse = (ServiceResponse) o;
    return Objects.equals(this.list, serviceResponse.list);
  }

  @Override
  public int hashCode() {
    return Objects.hash(list);
  }


  @Override
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ServiceResponse {\n");

    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

